### ISSUE TITLE
Upgrade all 3 LocalLayer widgets to v2.2

### ISSUE THREAD

**Issue by torrin47** [USEPA/EnviroAtlas_JSApp#66]
This might be our heaviest lift on the WebAppBuilder update front, as this was possibly the widget we put the most customization into. That said, it's well worth a thorough review to see whether we can take advantage of any upgrades/bugfixes/stability improvements.  
https://github.com/cmndrbensisko/LocalLayer
This would apply to BoundaryLayer, LocalLayer, and PeopleAndBuiltSpaces. While we're at it, if there's any way to move code that's common to all three widgets to some sort of shared location so we don't have to make updates three times, it would be worthwhile.

**Comment by Baohong** [comment]
The code that's common to all three widget has been moved to jimu/utils.js. 
There are truly many updates from https://github.com/cmndrbensisko/LocalLayer, such as addressing the newly added attribe in config.json and enriching the kinds of layers (GEOJSON, WMS etc) which could be added to map. Since we do not have such attributes in config and we do not have such layers in config, I omitted some of the updates--- we can not test even if all updates are included. I have included the rest updates, mostly for DYNAMIC layers. 
There is a sample config file in https://github.com/cmndrbensisko/LocalLayer. If we want to see what new advances in detail,  we should play a little bit more on that.
