### ISSUE TITLE
Download Elevation Profile generates error at 2.5

### ISSUE THREAD

**Issue by torrin47** [USEPA/EnviroAtlas_JSApp#72]
This is cool new functionality, but it's giving us an error:  
"Not allowed to navigate top frame to data URL:"
Forcing user to right-click and save-as.  Differs from Robert's demo site:
http://gis.calhouncounty.org/WAB/V2.5/widgets/ElevationProfile/index.html#
Can we fix this or is there something unique about EnviroAtlas that means we'll have to use right-click method and just train users?

**Comment by Baohong** [comment]
I have spent some time on this issue, finding that it is caused by index.html. We have a "Google Tag Manager" at the end of the file. If that part is removed, Elevation profile will perform the same way as Robert's demo site.
A testing version can be found on https://leb.epa.gov/Projects/EnviroAtlas/CurrentDevelopment/EnviroAtlas_JSApp/#. It is the same with the code of our EnviroAtlas version 2.5, except for the removing of  "Google Tag Manager" part.
But I still could not figure out a way of solving this problem with  "Google Tag Manager" added back.
Any suggestions?
