### ISSUE TITLE
ECAT is not always drawing

### ISSUE THREAD

**Issue by Baohong** [USEPA/EnviroAtlas_JSApp#90]

**Comment by Baohong** [comment]
ECAT result is not drawing on https://leb.epa.gov/EnviroAtlas_WAB/.
While it draws properly on https://leb.epa.gov/EnviroAtlas_2/.
So which is with the master branch? https://leb.epa.gov/EnviroAtlas_WAB/? Or https://leb.epa.gov/EnviroAtlas_2/?

**Comment by brosenbaum** [comment]
Currently, EnviroAtlas_WAB is the master ( https://leb.epa.gov/EnviroAtlas_WAB/ ). This is the branch/application  we should use. Torrin did a git pull on EnviroAtlas_WAB yesterday so it should be the same code as  https://leb.epa.gov/EnviroAtlas_2/. 

I was having different responses from the same version of the application and it didn't matter which browser.

So - Still having odd issues with ECAT tool - process will finish but not return map. Need to troubleshoot/correct.

And, I still wonder if we could convert the GP service a raster function on the mosaic dataset since it's a python script? just a thought...

**Comment by Baohong** [comment]
There is a bug in widgets/LayerList/css/style.css of the Production_Branch. Now the bug has been removed and code has been committed to Production_Branch. Please make same change for the three production servers and see whether ECAT problem could be fixed.

**Comment by brosenbaum** [comment]
thanks Baohong - I will push that change to production.

**Comment by brosenbaum** [comment]
change is pushed - need everyone to test this, please!

**Comment by torrin47** [comment]
Problem mostly caused by incorrect configuration of loadbalancer (no persistence set). Working on fixing this. For now, only using one server.

**Comment by brosenbaum** [comment]
load balancer has been modified - appears to be working but would like everyone to check this.

saw some unrelated but noted issues when testing. will open other tickets/issues for those.
