### ISSUE TITLE
Help dialog for ECAT tool isn't working

### ISSUE THREAD

**Issue by torrin47** [USEPA/EnviroAtlas_JSApp#93]
In chrome the grey background does funky things, and in Edge the modal can't be closed.

**Comment by brosenbaum** [comment]
Baohong has pushed a change so the help dialog comes up in a new pop-up window. Th push has been made to production so that the errors are not continuing for users. 

We may want to tweak formatting since the text runs all the way to the edge of the box and font has serifs. Do you have time for that Torrin?

**Comment by torrin47** [comment]
Made updates and committed to master - separate push to production?
